#!/bin/bash

# options:
#  rock [-t zxn|gcc] [--target=zxn|gcc] [--debug] filename

ROCK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLIB=sdcc_iy    # z88dk main library

transpile() {
  local target="$1" exe_abs="$2" source_abs="$3"
  "$ROCK_ROOT/rockc" "${source_abs}" "${exe_abs}" "--target=${target}"
}

build() {
  local target="$1" exe_abs="$2" sourcefile="$3"

  echo "compile $sourcefile -> $exe_abs"

  local RT="${ROCK_ROOT}/src"
  local LIB_SRCS="$RT/lib/alloc.c $RT/lib/fundefs.c $RT/lib/fundefs_internal.c $RT/lib/asm_interop.c"

  if [ "$target" = "gcc" ]; then
    gcc -Wall -Wno-unused-variable -I "${RT}/lib" -o "${exe_abs}" "${exe_abs}.c" ${LIB_SRCS}
  else
    zcc +zxn -vn -subtype=nex -startup=1 -clib=$CLIB -create-app \
      -pragma-include:"${RT}/lib/zxn/zpragma_zxn.inc" \
      -I"${RT}/lib" \
      -o "${exe_abs}" \
      "${exe_abs}.c" ${LIB_SRCS}
  fi
  if [ $? -eq 0 ]; then
    if [ "$target" = "gcc" ]; then
      echo "created $exe_abs"
    else
      rm -f "${exe_abs}"
      local nex_file="${exe_abs%%.*}.nex"
      echo "created $nex_file"
    fi
  fi
}


set -e
DEBUG=0

sourcefile=""
target="gcc"

while [ $# -gt 0 ]; do
  case "$1" in
    -t)
      target="${2}"
      shift 2
      ;;

    --target=*)
      target="${1#--target=}"
      shift
      ;;

    --debug)
      DEBUG=1; shift;;

    *) if [ "$sourcefile" = "" ]; then
         sourcefile="$1"
         source_dir=$(cd "$(dirname "$sourcefile")" && pwd)
         source_abs="${source_dir}/$(basename "$sourcefile")"
         exe_abs="${source_dir}/$(basename "${sourcefile%.*}").exe"
       else
         exe_abs="$1"
       fi
       shift
       ;;
  esac
done

[ $DEBUG -eq 1 ] && echo "target=$target exe=$exe_abs"
transpile "$target" "$exe_abs" "$source_abs"
build "$target" "$exe_abs" "$sourcefile"

if [ $DEBUG -eq 0 ]; then
  rm -f "${exe_abs}.c"
else
  clang-format -i "${exe_abs}.c"
fi
