#! /bin/bash

echo "zcc invoked with: $@"
echo "---------------------------------"

if [ "$1" = "run" ]; then
  shift 1
  F="$1.nex"
  if [ ! -f "$F" ]; then
    echo "Error,cant find $F file to run" 
    exit 1
  fi
  $HOME/bin/zx $F

else
  # *all* of this mess is used internally by z88dk :(
  export Z88BASE=$HOME/bin
  export Z88DK=${Z88BASE}/z88dk
  export Z88DK_DIR=z88dk
  export Z80_OZFILES=${Z88DK}/lib/clibs
  export ZCCCFG=${Z88DK}/lib/config

  export PATH=$Z88DK/bin:$PATH
  zcc "$@"
fi
